<a href="https://colab.research.google.com/github/Tadaa25/preprocessing/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
dataset = pd.read_csv('Wholesale customers data.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[    2     3 12669 ...  7561   214  2674]
 [    2     3  7057 ...  9568  1762  3293]
 [    2     3  6353 ...  7684  2405  3516]
 ...
 [    2     3 14531 ... 30243   437 14841]
 [    1     3 10290 ...  2232  1038   168]
 [    1     3  2787 ...  2510    65   477]]


In [5]:
print(Y)

[ 1338  1776  7844  1788  5185  1451   545  2566   750  2098  1744   497
  2931   602  2168   412  1080  4478  3181   501  2124   569  4334 16523
  5778    57   833   518  5206   823  2963   985   405  1083   395   436
  4626   714   433  2916  5864  2802    46    72    65  4985  1452  6465
  1476  1163  2162   301  1278   224  1333  1130  1340  1282   436  1603
   225  2017   964  1295  1145  1423    27   834  3095   144  1365 14472
   181   648  1780   975   894  1009   167  1653   529   156  2342   772
   120  2944   903 14351    46  3178   360  1117  5130  2698   244   709
   217    63   132   323  3029  1838  1386  2498   548  1378  1831  1438
  1236     3  1647  1519  2708  1561  1266   610   222  1160   933   635
  1136   255   860   143  1621   918   483  2749     3  1819   911   310
   328   396   537   326  1542    36  3271   929  2616  1450     3   318
   201  4430   520   526   434  1440  1067  1774   184  1627     8  2153
  3182   418  1682   303  2157  2233   610   446   

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
print(X)

[[0.0000e+00 1.0000e+00 3.0000e+00 ... 7.5610e+03 2.1400e+02 2.6740e+03]
 [0.0000e+00 1.0000e+00 3.0000e+00 ... 9.5680e+03 1.7620e+03 3.2930e+03]
 [0.0000e+00 1.0000e+00 3.0000e+00 ... 7.6840e+03 2.4050e+03 3.5160e+03]
 ...
 [0.0000e+00 1.0000e+00 3.0000e+00 ... 3.0243e+04 4.3700e+02 1.4841e+04]
 [1.0000e+00 0.0000e+00 3.0000e+00 ... 2.2320e+03 1.0380e+03 1.6800e+02]
 [1.0000e+00 0.0000e+00 3.0000e+00 ... 2.5100e+03 6.5000e+01 4.7700e+02]]


In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Loop semua kolom
for i in range(X.shape[1]):
    if isinstance(X[0, i], str):  # kalau masih string, ubah jadi numerik
        X[:, i] = le.fit_transform(X[:, i])


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [11]:
print(X_train)

[[1.0000e+00 0.0000e+00 3.0000e+00 ... 7.6400e+02 4.5100e+03 9.3000e+01]
 [0.0000e+00 1.0000e+00 2.0000e+00 ... 1.9172e+04 1.2740e+03 1.7120e+04]
 [1.0000e+00 0.0000e+00 3.0000e+00 ... 3.0090e+03 4.3000e+02 6.1000e+02]
 ...
 [0.0000e+00 1.0000e+00 3.0000e+00 ... 9.3450e+03 2.6440e+03 3.3780e+03]
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 2.8240e+03 1.2180e+03 1.2160e+03]
 [0.0000e+00 1.0000e+00 3.0000e+00 ... 1.2477e+04 1.9200e+03 6.5060e+03]]


In [12]:
print(X_test)

[[1.0000e+00 0.0000e+00 3.0000e+00 2.5767e+04 3.6130e+03 2.0130e+03
  1.0303e+04 3.1400e+02]
 [1.0000e+00 0.0000e+00 3.0000e+00 6.2110e+03 3.3700e+02 6.8300e+02
  1.0890e+03 4.1000e+01]
 [0.0000e+00 1.0000e+00 1.0000e+00 2.5410e+03 4.7370e+03 6.0890e+03
  2.9460e+03 5.3160e+03]
 [0.0000e+00 1.0000e+00 2.0000e+00 1.6448e+04 6.2430e+03 6.3600e+03
  8.2400e+02 2.6620e+03]
 [1.0000e+00 0.0000e+00 3.0000e+00 8.6070e+03 1.7500e+03 3.5800e+03
  4.7000e+01 8.4000e+01]
 [1.0000e+00 0.0000e+00 3.0000e+00 2.6400e+04 1.3770e+03 4.1720e+03
  8.3000e+02 9.4800e+02]
 [0.0000e+00 1.0000e+00 3.0000e+00 4.4466e+04 5.4259e+04 5.5571e+04
  7.7820e+03 2.4171e+04]
 [1.0000e+00 0.0000e+00 3.0000e+00 3.5210e+03 1.0990e+03 1.9970e+03
  1.7960e+03 1.7300e+02]
 [1.0000e+00 0.0000e+00 1.0000e+00 2.5962e+04 1.7800e+03 3.8380e+03
  6.3800e+02 2.8400e+02]
 [0.0000e+00 1.0000e+00 3.0000e+00 2.2615e+04 5.4100e+03 7.1980e+03
  3.9150e+03 1.7770e+03]
 [1.0000e+00 0.0000e+00 3.0000e+00 1.0290e+04 1.9810e+03 2.2320e+03
  

In [13]:
print(Y_train)

[ 2346   142   529  1452   712  2944   532   156   291  1092  1111   375
  2204  2794   254   497   379   689  2698  3137   229  2802   727  1970
   709  1831  5130    27   558 16523  5609   602     3  2017     3   791
   548  1386  2916  2233  1856   980   132  1115   211   834  2784  1215
  2749  2342  1902  3486   518  3178   868   648   144    51  1117    84
   303  1534   918  1603  1136  2931  1498   409    52   247   418   741
   659  1468  2341  1114  1827   259    46   310  1621  1040  2168   379
  1153   143  3271  1519   301  2708  2098   203  1080  4829  1338    59
  1378     7   249  1371  2235  1365  4365   433  1067   987   446   693
  1043   239  1328   993  4430    18   573  1233    46  2157  1892   225
   743   578   395  1360   776  1117   216  1163   447   526   659  3029
   395   404  1647  1697   224   326  5137     8   501     3    56  1682
  1037    65   898  2410  1561   668  2870  1236  1426   750  1653   290
  1854   120   750   405   323   270  4100   445   

In [14]:
print(Y_test)

[1384  296  120 2005 2501 1218 6465  995  834 5185 2125 2893 1894 2165
 1681 1543  860  373   62 1824 1438 1451 3113  776 1522 1442 4478  710
  610  716  287 1550  964  806  610  929  303  553  823 3105 3628  238
  960 2137 2379  707  139 1027   70 1874 1423  550  452 1784  360  684
  179  167 6372 6250 1060  834 1160  429 2158  545  967  328  117 1838
 5121 1022  361 1328  436  739  285  686  520  806  128 3181 5864  405
 2406  635  786 3321]


In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [16]:
print(X_train)

[[ 1.          0.          3.         ... -0.7518673   0.26807336
  -0.58190119]
 [ 0.          1.          2.         ...  1.1684481  -0.35596584
   2.96761527]
 [ 1.          0.          3.         ... -0.51766977 -0.51872514
  -0.4741253 ]
 ...
 [ 0.          1.          3.         ...  0.14329929 -0.09177124
   0.10290304]
 [ 1.          0.          1.         ... -0.5369689  -0.36676504
  -0.34779612]
 [ 0.          1.          3.         ...  0.47002831 -0.23138941
   0.75497842]]


In [17]:
print(X_test)

[[ 1.00000000e+00  0.00000000e+00  3.00000000e+00  1.07946465e+00
  -3.00043784e-01 -6.21572103e-01  1.38521153e+00 -5.35830642e-01]
 [ 1.00000000e+00  0.00000000e+00  3.00000000e+00 -4.64297633e-01
  -7.42002333e-01 -7.60317185e-01 -3.91641753e-01 -5.92741313e-01]
 [ 0.00000000e+00  1.00000000e+00  1.00000000e+00 -7.54009617e-01
  -1.48407212e-01 -1.96365368e-01 -3.35327281e-02  5.06906263e-01]
 [ 0.00000000e+00  1.00000000e+00  2.00000000e+00  3.43817241e-01
   5.47642090e-02 -1.68094753e-01 -4.42745087e-01 -4.63571810e-02]
 [ 1.00000000e+00  0.00000000e+00  3.00000000e+00 -2.75155967e-01
  -5.51377354e-01 -4.58103272e-01 -5.92583920e-01 -5.83777361e-01]
 [ 1.00000000e+00  0.00000000e+00  3.00000000e+00  1.12943404e+00
  -6.01698032e-01 -3.96346062e-01 -4.41588031e-01 -4.03664469e-01]
 [ 0.00000000e+00  1.00000000e+00  3.00000000e+00  2.55557484e+00
   6.53250588e+00  4.96557763e+00  8.99054910e-01  4.43749490e+00]
 [ 1.00000000e+00  0.00000000e+00  3.00000000e+00 -6.76647834e-01
  -