In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [6]:
dataset = pd.read_csv('dataset_renang.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[1 'Alya' 16 'Laki-laki' 'Menengah' 94.7 1946.3 4 'Kupu-kupu' 293.6
  'Lomba' 2 'Cerah' 29.9]
 [2 'Budi' 29 'Perempuan' 'Menengah' 74.0 1712.9 1 'Kupu-kupu' 637.7
  'Kesehatan' 6 'Hujan' 30.5]
 [3 'Citra' 38 'Perempuan' 'Pemula' 78.7 1471.3 6 'Bebas' 709.3
  'Kesehatan' 3 'Hujan' 24.5]
 [4 'Dewi' 24 'Perempuan' 'Mahir' 116.5 548.4 1 'Punggung' 290.1 'Lomba'
  9 'Cerah' 25.5]
 [5 'Eko' 20 'Laki-laki' 'Menengah' 80.7 586.5 1 'Bebas' 682.6
  'Kesehatan' 4 'Cerah' 28.7]
 [6 'Farhan' 17 'Perempuan' 'Pemula' 47.6 176.8 1 'Punggung' 394.2
  'Lomba' 1 'Mendung' 26.5]
 [7 'Gita' 38 'Laki-laki' 'Pemula' 49.6 1450.3 3 'Dada' 605.8 'Kesehatan'
  4 'Cerah' 25.8]
 [8 'Hadi' 30 'Laki-laki' 'Pemula' 36.5 310.7 6 'Dada' 606.8 'Kesehatan'
  1 'Mendung' 26.1]
 [9 'Indra' 16 'Laki-laki' 'Pemula' 21.6 934.7 1 'Dada' 528.6 'Rekreasi'
  5 'Cerah' 26.3]
 [10 'Joko' 35 'Laki-laki' 'Menengah' 62.3 483.3 4 'Kupu-kupu' 172.2
  'Rekreasi' 4 'Mendung' 29.9]
 [11 'Kiki' 28 'Laki-laki' 'Menengah' 59.5 1802.0 5 'Dada

In [7]:
print(Y)

[2 5 2 2 1 4 2 3 4 5 1 5 4 4 4 5 4 5 4 3 4 5 2 4 2 3 1 3 4 2]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 2 'Cerah' 29.9]
 [0.0 1.0 0.0 ... 6 'Hujan' 30.5]
 [0.0 0.0 1.0 ... 3 'Hujan' 24.5]
 ...
 [0.0 0.0 0.0 ... 1 'Cerah' 27.1]
 [0.0 0.0 0.0 ... 1 'Mendung' 28.7]
 [0.0 0.0 0.0 ... 5 'Hujan' 26.3]]


In [35]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# encode kolom 'Cuaca'
X[:, -2] = le.fit_transform(X[:, -2])

# encode kolom 'Tujuan'
X[:, -4] = le.fit_transform(X[:, -4])

# encode kolom 'Gaya_Utama'
X[:, -7] = le.fit_transform(X[:, -7])

# encode kolom 'Tingkat_Kemampuan'
X[:, -10] = le.fit_transform(X[:, -10])

# encode kolom 'Jenis_Kelamin'
X[:, -11] = le.fit_transform(X[:, -11])


In [36]:
print(X)

[[1.0 0.0 0.0 ... 2 0 29.9]
 [0.0 1.0 0.0 ... 6 1 30.5]
 [0.0 0.0 1.0 ... 3 1 24.5]
 ...
 [0.0 0.0 0.0 ... 1 0 27.1]
 [0.0 0.0 0.0 ... 1 2 28.7]
 [0.0 0.0 0.0 ... 5 1 26.3]]


In [41]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Loop semua kolom
for i in range(X.shape[1]):
    if isinstance(X[0, i], str):  # kalau masih string, ubah jadi numerik
        X[:, i] = le.fit_transform(X[:, i])


In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [43]:
print(X_train)

[[0.0 0.0 0.0 ... 5 2 28.1]
 [0.0 0.0 0.0 ... 9 0 25.5]
 [0.0 0.0 0.0 ... 8 0 30.2]
 ...
 [0.0 0.0 0.0 ... 7 0 27.9]
 [0.0 0.0 0.0 ... 8 0 29.0]
 [0.0 0.0 0.0 ... 1 2 26.5]]


In [44]:
print(X_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 22 17 1 2 112.6 485.8 4
  3 509.7 2 6 1 24.6]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 26 30 0 1 64.9 1772.9 3
  1 652.8 2 6 0 24.5]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 13 28 0 1 59.5 1802.0 4
  1 768.2 0 8 1 25.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 24 12 0 2 111.5 1237.8
  2 2 616.1 1 6 0 28.4]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 18 33 1 2 91.1 364.7 2
  0 572.7 2 1 0 26.9]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 25 31 1 0 105.0 1420.1
  1

In [45]:
print(Y_train)

[0 1 1 1 3 0 1 2 1 3 3 2 2 4 3 1 4 1 3 4 3 3 4 3]


In [46]:
print(Y_test)

[4 4 0 2 3 3]


In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [48]:
print(X_train)

[[0.0 0.0 0.0 ... 0.35893503009349875 1.507556722888818
  0.5109649665079495]
 [0.0 0.0 0.0 ... 1.999780881949493 -0.9045340337332909
  -0.8287078868574309]
 [0.0 0.0 0.0 ... 1.5895694189854945 -0.9045340337332909
  1.5930084249953704]
 ...
 [0.0 0.0 0.0 ... 1.179357956021496 -0.9045340337332909
  0.40791320855676505]
 [0.0 0.0 0.0 ... 1.5895694189854945 -0.9045340337332909
  0.9746978772882725]
 [0.0 0.0 0.0 ... -1.2819108217624955 1.507556722888818
  -0.3134490971015156]]


In [49]:
print(X_test)

[[0.0 0.0 0.0 -0.2085144140570746 -0.20851441405707463
  -0.20851441405707474 -0.20851441405707466 -0.20851441405707466
  -0.20851441405707472 -0.2085144140570747 0.0 -0.20851441405707474
  -0.20851441405707472 -0.20851441405707466 0.0 -0.2085144140570747
  -0.2085144140570747 1.0 -0.20851441405707466 0.0 0.0 0.0
  -0.20851441405707463 -0.20851441405707463 -0.20851441405707463
  -0.20851441405707466 -0.2085144140570746 -0.20851441405707466
  -0.2085144140570747 -0.2085144140570747 1.071062823796571
  -0.9134801190523368 1.0 1.1180339887498947 1.91818090719034
  -1.051321269714053 1.0113917425784182 1.6059101370939322
  0.2832201693649954 1.6081688022566925 0.7691464930574974
  0.30151134457776363 -1.2924407976377539]
 [0.0 0.0 0.0 -0.2085144140570746 -0.20851441405707463
  -0.20851441405707474 -0.20851441405707466 -0.20851441405707466
  -0.20851441405707472 -0.2085144140570747 0.0 -0.20851441405707474
  -0.20851441405707472 -0.20851441405707466 0.0 -0.2085144140570747
  -0.208514414057